project:
  type: book
  output-dir: docs

book:
  title: ENEM
  subtitle: Análise dos microdados ENEM 2021
  author: Paulo Ricardo Seganfredo Campana
  date: today
  chapters:
    - index.qmd
    - chapters/1-limpeza.qmd
    - chapters/2-análise-exploratória.qmd
    - chapters/3-modelagem.qmd
  repo-url: https://github.com/PauloCampana/ENEM
  cover-image: misc/cover.png
  sidebar:
    background: "#21252b"

lang: pt
cache: true
warning: false

theme: [darkly, misc/custom.scss]
backgroundcolor: "#282c34"
code-block-bg: "#21252b"
code-block-border-left: "#00bc8c"
highlight-style: atom-one
code-link: true
code-tools: true